import pygame;
import pygame.font;

pygame.init()

# This File defines all the constants used for Colours, Sizes,...

# GAME-WINDOW VARIABLES
FRAMES_PER_SECOND = 120
SCREEN_WIDTH = 1148
SCREEN_HEIGHT = 720

# MOBS
MOB_TYPES = ["Player","Aberga","Rocker","Ilog"]
ANIMATION_COOLDOWN = 70

# Player
PLAYER_HEIGHT = 48
PLAYER_WIDTH = 32
PLAYER_SPEED = 3
PLAYER_OFFSET = 12
PENCIL_SPEED = 10
P_DAMAGE_BASE = 10
P_DAMAGE_EXTRA = 5
P_HIT_COOLDOWN = 500 # in miliseconds

# Aberga
ABERGA_HEALTH = 100
ABERGA_HEIGHT = 48
ABERGA_WIDTH = 32
ABERGA_SPEED = 2
ABERGA_RANGE = 51
ABERGA_DAMAGE = 10
ABERGA_STUN_COOLDOWN = 100

# Rocker
ROCKER_HEALTH = 100
ROCKER_HEIGHT = 48
ROCKER_WIDTH = 32
ROCKER_SPEED = 2
ROCKER_RANGE = 51
ROCKER_DAMAGE = 20
ROCKER_STUN_COOLDOWN = 100

# Ilog
ILOG_HEALTH = 100
ILOG_HEIGHT = 96
ILOG_WIDTH = 32
ILOG_SPEED = 2
ILOG_RANGE = 51
ILOG_DAMAGE = 50
ILOG_STUN_COOLDOWN = 100
PUCK_COOLDOWN = 500
RANGE = 50
FIREBALL_SPEED = 4

# SCALES
GAME_SCALE = 2
BUTTON_SCALE = 1
COIN_SCALE = 1
POTION_SCALE = 2
PIZZA_SCALE = 1
FIREBALL_SCALE = 1
WEAPON_SCALE = 1.5
SHOP_TILE_SCALE = 4
BRISN_SCALE = 2
HEART_SCALE = 3

# TILE-VARIABLES
TILE_SIZE = 16 * GAME_SCALE
TILE_TYPES = 114
LEVEL_NAMES = ["3AHINF","GANG","3BHME","GANG","4BHME","GANG","2BHME","GANG","5BHME","GANG","COUCHES"]
EXIT_SCALE = 4
MAIN_FONT = pygame.font.Font("Game/assets/fonts/MainFont.ttf",35)

ROWS = 50
COLS = 150
SCROLL_THRES = 300


# SCHANZENSHOP
SHOP_WIDTH = 64
SHOP_HEIGHT = 64
SHOP_RANGE = 64

# Item-Price
SHOP_POTION_BASE = 2
SHOP_BRISN_BASE = 2
SHOP_ROCKERFLASCHE_BASE = 2

SHOP_POTION_INCR = 2
SHOP_BRISN_INCR = 4
SHOP_ROCKERFLASCHE_INCR = 666

# Item-Effect
POTION_HEAL = 20
BRISN_DAMAGE = 50
BRISN_ATTACK_BOOST = 100


# COLORS
WHITE = (255, 255, 255)
RED = (255,0,0)
BLACK = (0, 0, 0)
PINK = (235, 65, 54)
BACKGROUND = (204,204,204)
MENU_BG = (0,0,0)
WHITE = (255, 255, 255)
PANEL = (50,50,50)
YELLOW = (255,215,0)